#!/usr/bin/env node

require('proof')(9, prove)

function prove (assert) {
    var hilbert = require('../..')
    assert(hilbert.hilbertInverse(2, 2), [0, 0])
    assert(hilbert.hilbertInverse(2, 3), [0, 1])
    assert(hilbert.hilbertInverse(2, 4), [2, 0])
    assert(hilbert.hilbertInverse(2, 15), [3, 0])
    assert(hilbert.hilbertInverse(2, 16), [0, 4])
    assert(hilbert.hilbertInverse(2, 63), [7, 0])
    assert(hilbert.hilbertInverse(2, 64), [0, 8])
    assert(hilbert.hilbertInverse(2, 1023), [31, 0])
    assert(hilbert.hilbertInverse(2, 1024), [0, 32])
    console.log("0 " , hilbert.hilbertInverse(2,0))
    console.log("1 " , hilbert.hilbertInverse(2,1))
    console.log("2 " , hilbert.hilbertInverse(2,2))
    console.log("3 " , hilbert.hilbertInverse(2,3))
    console.log("4 " , hilbert.hilbertInverse(2,4))
    console.log("5 " , hilbert.hilbertInverse(2,5))
    console.log("6 " , hilbert.hilbertInverse(2,6))
    console.log("7 " , hilbert.hilbertInverse(2,7))
    console.log("8 " , hilbert.hilbertInverse(2,8))
    console.log("9 " , hilbert.hilbertInverse(2,9))
    console.log("10 " , hilbert.hilbertInverse(2,10))
    console.log("11 " , hilbert.hilbertInverse(2,11))
    console.log("12 " ,hilbert.hilbertInverse(2,12))
    console.log("13 " ,hilbert.hilbertInverse(2,13))
    console.log("14 " ,hilbert.hilbertInverse(2,14))
    console.log("15 " ,hilbert.hilbertInverse(2,15))
    console.log("16 " ,hilbert.hilbertInverse(2,16))
}
